---
- name: Web servers configuration
  hosts: all
  become: true

  roles:
    - deploy_nginx_web
    - tls_cert_and_renew

  tasks:
    - name: Debug 3
      ansible.builtin.debug:
        msg: "{{ domain_name }}"


    # - name: Create /etc/letsencrypt/live/ directory
    #   ansible.builtin.file:
    #     path: "/home/{{ username }}/.ssh/"
    #     state: directory
    #     mode: '644'

    # - name: Transfer private key to remote host
    #   ansible.builtin.copy:
    #     src: "{{ private_key }}"
    #     dest: "/home/{{ username }}/.ssh/{{ private_key }}"
    #     mode: '644'
