---
- name: nginx configuration
  hosts: all
  become: yes

  roles:
    - tls_cert_and_renew
  
  tasks:

  - name: Include encrypted vars
    include_vars: encryptedvars.yml

  - name: debug 3
    debug:
      msg: "/home/{{ username }}/.ssh/{{ private_key }}"

  - name: Create home/username/.ssh/ directory
    file:
      path: "/home/{{ username }}/.ssh/"
      state: directory

  - name: Transfer private key to remote host
    copy:
      src: "{{ private_key }}"
      dest: "/home/{{ username }}/.ssh/{{ private_key }}"
