---
- name: nginx configuration
  hosts: all
  become: yes

###############

  vars:
  # virtualhosts vars
    files:
      vh1: "virtualhost1.conf.j2"
      vh2: "virtualhost2.conf.j2"
    vh1_listen_port: 80
    vh2_listen_port: 443
    sites_available: "/etc/nginx/sites-available/"
  # nginx vars
    nginx_src: "nginx.conf.j2"
    nginx_dest: "/etc/nginx/nginx.conf"
    # enter "#" or "" to switch off/switch on mail module in nginx.conf
    mail_module_onoff: "#"
    worker_connections: 768
    keepalive_timeout: 65
    types_hash_max_size: 2048
    pop3_localhost: 110
    imap_localhost: 143
    sites_enabled: "/etc/nginx/sites-enabled/"
    access_log: "/var/log/nginx/access.log"
    error_log: "/var/log/nginx/error.log"
###############

  tasks:
  - name: apt-get update
    apt:
      update_cache: yes

  - name: Nginx install
    apt:
      name: nginx=1.18.0-0ubuntu1.4
      state: present
      #name: nginx
      #state: latest

  - name: Start nginx service
    service:
      name: nginx
      state: restarted
      enabled: yes

  - block:   #Reload after generating new configs#
      - name: Generate Virtualhosts files
        template:
          src: "{{ item.value }}"
          dest: "{{ sites_available }}{{ item.value | regex_replace('.j2','') }}"
        loop: "{{ lookup('dict', files) }}"

      - name: Generate Nginx config
        template:
          src: "{{ nginx_src }}"
          dest: "{{ nginx_dest }}"

      - name: Remove default config from sites-enabled
        file:
          path: "{{ sites_enabled }}default"
          state: absent
    notify: Nginx reload

  - name: Create symlinks for virtualhosts
    shell: "ln -s {{ sites_available }}{{ item.value | regex_replace('.j2','') }} {{ sites_enabled }}{{ item.value | regex_replace('.j2','') }}"
    loop: "{{ lookup('dict', files) }}"

###############

  handlers:
  - name: Nginx reload
    service:
      name: nginx
      state: reloaded
