---
- name: nginx configuration
  hosts: all
  become: yes

###############

  vars:
    vhport: ""
  # virtualhosts vars
    vh_temp_file: "templates/virtualhost.conf.j2"
    vh_files:
      vh1:
        vh_name: "virtualhost1.conf"
        vh_port: 80
        html_path: "web1"
      vh2:
        vh_name: "virtualhost2.conf"
        vh_port: 443
        html_path: "web2"

    sites_available: "/etc/nginx/sites-available/"
  # nginx vars
    nginx_src: "templates/nginx.conf.j2"
    nginx_dest: "/etc/nginx/nginx.conf"
    # enter "#" or "" to switch off/switch on mail module in nginx.conf
    mail_module_onoff: "#"
    worker_connections: 768
    keepalive_timeout: 65
    types_hash_max_size: 2048
    pop3_localhost: 110
    imap_localhost: 143
    sites_enabled: "/etc/nginx/sites-enabled/"
    access_log: "/var/log/nginx/access.log"
    error_log: "/var/log/nginx/error.log"
  # index.html vars
    index_temp_file: "templates/index.html.j2"
    web1_user_names:
      - "Vasya"
      - "Petya"
      - "Kolya"
    web2_user_names:
      - "Anton"
      - "Alex"
      - "Sergey"

###############

  tasks:
    
  - name: apt-get update
    apt:
      update_cache: yes

  - name: Nginx install
    apt:
      name: nginx=1.14.0-0ubuntu1.11
      state: present
      #name: nginx
      #state: latest
    notify: Start nginx service


  - name: Generate Virtualhosts files
    template:
      src: "{{ vh_temp_file }}"
      dest: "{{ sites_available }}{{ item.value.vh_name }}"
    loop: "{{ lookup('dict', vh_files) }}"
    notify: Nginx reload

  - name: Generate Nginx config
    template:
      src: "{{ nginx_src }}"
      dest: "{{ nginx_dest }}"
    notify: Nginx reload

  - name: Create /var/www/html/ directory
    file:
      path: "/var/www/html/{{ item.value.html_path }}"
      state: directory
    loop: "{{ lookup('dict', vh_files) }}"

  - name: Generate index.html files
    template:
      src: "{{ index_temp_file }}"
      dest: "/var/www/html/{{ item.value.html_path }}/index.html"
    loop: "{{ lookup('dict', vh_files) }}"
    notify: Nginx reload

  - name: Remove default config from sites-enabled
    file:
      path: "{{ sites_enabled }}default"
      state: absent

  - name: Create symlinks for virtualhosts
    file:
      src: "{{ sites_available }}{{ item.value.vh_name }}"
      dest: "{{ sites_enabled }}{{ item.value.vh_name }}"
      state: link
    loop: "{{ lookup('dict', vh_files) }}"

###############

  handlers:
  - name: Nginx reload
    service:
      name: nginx
      state: reloaded

  - name: Start nginx service
    service:
      name: nginx
      state: restarted
      enabled: yes
