---
- name: update
  yum:
    update_cache: yes

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: Nginx install
  yum:
    name: nginx-1.20.1-10.el7.x86_64
    state: present
  notify: Start nginx service