---
- name: Update and install Nginx for Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Update and install Nginx for Centos
  include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Generate Nginx config
  template:
    src: "{{ nginx_src }}"
    dest: "{{ nginx_dest }}"
  notify: nginx reload

- name: Create /var/www/html/ directory
  file:
    path: "/var/www/{{ ansible_host }}/html/"
    state: directory

- name: Generate index.html files
  template:
    src: "{{ index_temp_file }}"
    dest: "/var/www/{{ ansible_host }}/html/index.html"



