---
- name: Include nginx vars
  ansible.builtin.include_vars: vars{{ ansible_distribution }}.yml

- name: Debug 2
  ansible.builtin.debug:
    msg: "{{ nginx_version }}"

- name: Update and install Nginx
  ansible.builtin.include_tasks: ngx{{ ansible_distribution }}.yml

- name: Generate Nginx config
  ansible.builtin.template:
    src: "{{ nginx_src }}"
    dest: "{{ nginx_dest }}"
    mode: '644'
  notify: Nginx reload

- name: Create /var/www/html/ directory
  ansible.builtin.file:
    path: "/var/www/{{ domain_name }}/html/"
    state: directory
    mode: '755'
  when: "'app_srv' in group_names"

- name: Generate index.html files
  ansible.builtin.template:
    src: "{{ index_temp_file }}"
    dest: "/var/www/{{ domain_name }}/html/index.html"
    mode: '644'
  when: "'app_srv' in group_names"
