---

# - name: debug
#   debug:
#     msg: "{{ ansible_user }}"

- name: Include nginx vars
  include_vars: vars{{ ansible_distribution }}.yml

- name: debug 2
  debug:
    msg: "{{ nginx_version }}"

- name: Update and install Nginx
  include: ngx{{ ansible_distribution }}.yml

- name: Generate Nginx config
  template:
    src: "{{ nginx_src }}"
    dest: "{{ nginx_dest }}"
  notify: nginx reload

- name: Create /var/www/html/ directory
  file:
    path: "/var/www/{{ inventory_hostname }}/html/"
    state: directory

- name: Generate index.html files
  template:
    src: "{{ index_temp_file }}"
    dest: "/var/www/{{ inventory_hostname }}/html/index.html"



