---
- name: Update cache
  ansible.builtin.yum:
    update_cache: true

- name: Install epel-release
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Nginx install
  ansible.builtin.yum:
    name: "{{ nginx_version }}"
    state: present
  notify: Start nginx service
