---
- name: update
  yum:
    update_cache: yes

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: Nginx install
  yum:
    name: "{{ nginx_version }}"
    state: present
  notify: Start nginx service