---
- name: install certbot
  include: inst{{ ansible_distribution }}.yml


# - name: Let's Encrypt cert
#   shell: "certbot certonly --non-interactive --nginx --agree-tos --preferred-challenges http --email {{ email }} -d {{ inventory_hostname }}"

- name: Create /etc/letsencrypt/live/ directory
  file:
    path: "{{ tls_path }}{{ inventory_hostname }}/"
    state: directory

- name: Transfer TLS cert
  copy:
    src: "{{ tls_cert }}"
    dest: "{{ tls_path }}{{ inventory_hostname }}/{{ tls_cert }}"

- name: Transfer TLS key
  copy:
    src: "{{ tls_key }}"
    dest: "{{ tls_path }}{{ inventory_hostname }}/{{ tls_key }}"

- name: Generating Virtualhost file
  include: vh{{ ansible_distribution }}.yml

  