---
- name: install certbot for Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: install certbot for CentOS
  include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Let's Encrypt cert
  shell: "certbot certonly --non-interactive --nginx --agree-tos --preferred-challenges http --email {{ email }} -d {{ ansible_host }}"

- name: Virtualhost file for Ubuntu
  include: vhubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Virtualhost file for CentOS
  include: vhcentos.yml
  when: ansible_distribution == "CentOS"

  
