---
- name: Generate Virtualhost file
  ansible.builtin.template:
    src: "{{ vh_temp_file }}"
    dest: "{{ sites_available }}{{ inventory_hostname }}.conf"
    mode: '644'
  notify: Nginx reload

- name: Remove default config from sites-enabled
  ansible.builtin.file:
    path: "{{ sites_enabled }}default"
    state: absent
  notify: Nginx reload

- name: Create symlinks for virtualhosts
  ansible.builtin.file:
    src: "{{ sites_available }}{{ inventory_hostname }}.conf"
    dest: "{{ sites_enabled }}{{ inventory_hostname }}.conf"
    state: link
    mode: '644'
  notify: Nginx reload
