---
- name: apt-get update
  apt:
    update_cache: yes

- name: Nginx install
  apt:
    name: nginx=1.14.0-0ubuntu1.11
    state: present
    #name: nginx
    #state: latest
  notify: Start nginx service

- name: Generate Virtualhosts files
  template:
    src: "{{ vh_temp_file }}"
    dest: "{{ sites_available }}{{ item.value.vh_name }}"
  loop: "{{ lookup('dict', vh_files) }}"
  notify: Nginx reload

- name: Generate Nginx config
  template:
    src: "{{ nginx_src }}"
    dest: "{{ nginx_dest }}"
  notify: Nginx reload

- name: Create /var/www/html/ directory
  file:
    path: "/var/www/html/{{ item.value.html_path }}"
    state: directory
  loop: "{{ lookup('dict', vh_files) }}"

- name: Generate index.html files
  template:
    src: "{{ index_temp_file }}"
    dest: "/var/www/html/{{ item.value.html_path }}/index.html"
  loop: "{{ lookup('dict', vh_files) }}"
  notify: Nginx reload

- name: Remove default config from sites-enabled
  file:
    path: "{{ sites_enabled }}default"
    state: absent

- name: Create symlinks for virtualhosts
  file:
    src: "{{ sites_available }}{{ item.value.vh_name }}"
    dest: "{{ sites_enabled }}{{ item.value.vh_name }}"
    state: link
  loop: "{{ lookup('dict', vh_files) }}"
