---
# virtualhosts vars
  vh_temp_file: "virtualhost.conf.j2"
  vh_files:
    vh1:
      vh_name: "virtualhost1.conf"
      vh_port: 80
      html_path: "web1"
    vh2:
      vh_name: "virtualhost2.conf"
      vh_port: 443
      html_path: "web2"

  sites_available: "/etc/nginx/sites-available/"
# nginx vars
  nginx_src: "nginx.conf.j2"
  nginx_dest: "/etc/nginx/nginx.conf"
  # enter "#" or "" to switch off/switch on mail module in nginx.conf
  mail_module_onoff: "#"
  worker_connections: 768
  keepalive_timeout: 65
  types_hash_max_size: 2048
  pop3_localhost: 110
  imap_localhost: 143
  sites_enabled: "/etc/nginx/sites-enabled/"
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"
# index.html vars
  index_temp_file: "index.html.j2"
  web1_user_names:
    - "Vasya"
    - "Petya"
    - "Kolya"
  web2_user_names:
    - "Anton"
    - "Alex"
    - "Sergey"
